# $FreeBSD$

SCRIPTS=	MFCns_handler.py MFCns_stats.py
SCRIPTSNAME_MFCns_handler.py=	MFCns_handler.py

SCRIPTSDIR=	${MFCNSBINDIR}

MAN1=

SCRIPTSOWN=	${MFCNSOWN}
SCRIPTSGRP=	${MFCNSGRP}

.include <bsd.prog.mk>
